version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "CI: "

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "Cargo: "

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "Nix: "
