syntax = "proto3";

package neve.server.v1;

service AuthService {
  // Register an account in the server.
  rpc Register(RegisterRequest) returns (RegisterResponse);

  // Authenticate with the server using information from a registered account.
  //
  // This is required to interact with all other services.
  rpc Authenticate(AuthenticateRequest) returns (AuthenticateResponse);

  // Try authenticating if this account already exist, otherwise register first then authenticate.
  //
  // Equivalent to roughly:
  // - Authenticate()
  // - if err
  //   - Register()
  //   - Authenticate()
  rpc AuthenticateOrRegister(AuthenticateOrRegisterRequest) returns (AuthenticateOrRegisterResponse);
}

message RegisterRequest {
  // The username to register.
  string username = 1;

  // The password to associate with the username.
  string password = 2;
}

message RegisterResponse {
  // The ID of the account that was registered.
  int32 account_id = 1;
}

message AuthenticateRequest {
  // The username to use for authentication.
  string username = 1;

  // The password to use for authentication.
  string password = 2;
}

message AuthenticateResponse {
  // The token that associates requests to this account.
  //
  // This must be placed in all future requests sent to other services.
  string auth_token = 1;
}

message AuthenticateOrRegisterRequest {
  // The username to use for authentication or registration.
  string username = 1;

  // The password to use for authentication or registration.
  string password = 2;
}

message AuthenticateOrRegisterResponse {
  // The token that associates requests to this account.
  //
  // This must be placed in all future requests sent to other services.
  string auth_token = 1;
}
